<div id="menuwrapper">
<ul id="p7menubar">


<li><a class="trigger" href="#">Masters</a>
<ul>
<li><a href="Assessee.aspx?vtype=28">Assessee Master</a></li>
<li><a href="AssetMaster.aspx?vtype=45">Asset Master</a></li>
<li><a href="#">Partner Master</a></li>
<li><a href="#">Company Details</a></li>
  <li>
    <a href="DirectorMaster.aspx">Director Details</a>
  </li>
<li><a href="BankMaster.aspx">Bank Master</a></li>
<li><a href="Employermaster.aspx?vtype=31">Employer Master</a></li>
<li><a href="BusinessMaster.aspx">Business Master</a></li>
<li><a href="#">Tax Consultant Master</a></li>
<li><a href="Auditormaster.aspx">Auditor Master</a></li>
<li><a href="#">Exit</a></li>

</ul>
</li>

<li><a class="trigger" href="#">Computation Center</a>
<ul>
<li><a href="Salary.aspx?vtype=40">Salary</a></li>
<li><a href="Salary.aspx?vtype=42">House Property</a></li>
<li><a href="Salary.aspx?vtype=41">Business Profession</a></li>
<li><a href="Salary.aspx?vtype=43">Capital Gains</a></li>
<li><a href="salary.aspx?vtype=44">Other Sources</a></li>
<li>
  <a href="#">Deductions</a> 
  <li>
    <a href="salary.aspx?vtype=73">Deductions U/S 80C</a>
  </li>
  <li>
    <a href="salary.aspx?vtype=46">Other Deductions</a>
  </li>
</li>
  
  <li>
    <a href="salary.aspx?vtype=48">Exemptions</a>
  </li>
  <li>
    <a href="Salary.aspx?vtype=51">Clubbing of Income</a>
  </li>
  <li>
    <a href="#">Losses</a>
  </li>
  <li>
    <a href="#">Tax Deposited</a>
    <li>
      <a href="salary.aspx?vtype=49">Income Tax</a>
    </li>
    <li>
      <a href="salary.aspx?vtype=67">Dividend Distribution Tax</a>
    </li>
  </li>
  <li>
    <a href="salary.aspx?vtype=84">AIR Statement</a>
  </li>
</ul>
</li>

<li><a class="trigger" href="#">Accounts Information</a>
<ul>
<li><a href="salary.aspx?vtype=62">Balance Sheet</a></li>
<li><a href="salary.aspx?vtype=64">Depreciation Chart</a></li>
  <li>
    <a href="salary.aspx?vtype=63">Audit Report</a>
  </li>

</ul>
</li>

<li><a class="trigger" href="#">Fringe Benefit Tax</a>
<ul>
  <li>
    <a href="salary.aspx?vtype=90">FBT Details</a>
  </li>
  <li>
    <a href="salary.aspx?vtype=91">Tax Deposit</a>
  </li>
  <li>
    <a href="#">FBT Report</a>
  </li>
</ul>
</li>




<li><a href="javascript:void(0)" onclick="javascript:window.close();">Log out</a></li>
</ul>
<br class="clearit"/>
</div>